from ftplib import FTP

ftp = FTP('ftp.namethatthing.site')
ftp.login('EfraimFTP','G00dSh@bb0s')
ftp.cwd('public_html')
ftp.storbinary('STOR PDSocialBondingRW.html', open('../PDSocialBondingRW.html', 'rb'))
ftp.cwd('js')
ftp.storbinary('STOR getPFAPIDataRW.js', open('../js/getPFAPIDataRW.js', 'rb'))
ftp.storbinary('STOR PrintFulAPIRW.js', open('../js/PrintFulAPIRW.js', 'rb'))
# ftp.storbinary('STOR PDSBUtilities.js', open('../js/PDSBUtilities.js', 'rb'))
# ftp.storbinary('STOR PDSBAction.js', open('../js/PDSBAction.js', 'rb'))
ftp.storbinary('STOR oldJSRW.js', open('../js/oldJSRW.js', 'rb'))
# ftp.storbinary('STOR colorCodesRW.js', open('../js/colorCodesRW.js', 'rb'))
# ftp.storbinary('STOR oldJS2RW.js', open('../js/oldJS2RW.js', 'rb'))
ftp.storbinary('STOR menuRW.js', open('../js/menuRW.js', 'rb'))
# ftp.storbinary('STOR sizingInfo.js', open('../js/sizingInfo.js', 'rb'))
# ftp.storbinary('STOR HTMLTemplates.js', open('../js/HTMLTemplates.js', 'rb'))
ftp.storbinary('STOR PDSBProductDisplay.js', open('../js/PDSBProductDisplay.js', 'rb'))
ftp.storbinary('STOR dataCollection.js', open('../js/dataCollection.js', 'rb'))
ftp.cwd('../template')
ftp.storbinary('STOR prepPayForm.html', open('../template/prepPayForm.html', 'rb'))
# ftp.storbinary('STOR SBTShirtsRW.css', open('../css/SBTShirtsRW.css', 'rb'))
ftp.quit()
