function getReadyForPayPal(a){if(!PAYMENT_BEING_PROCESSED){var b=document.getElementById("dataGather"),c=document.getElementById("shoppingTable");document.getElementById("dGSubmit");document.getElementById("dGCancel");if(a){a=[];var e=!0;b=0;for(var d=1;d<c.rows.length-1;d++)b+=parseInt(c.rows[d].cells[1].innerHTML),itemName=c.rows[d].cells[0].innerHTML,itemName=itemName.substring(itemName.indexOf(">")+1,itemName.lastIndexOf("<")),a.push([itemName,c.rows[d].cells[1].innerHTML,c.rows[d].cells[2].innerHTML,
c.rows[d].cells[3].innerHTML,c.rows[d].cells[6].innerHTML,c.rows[d].cells[5].innerHTML]);d=document.getElementById("dGName");c=document.getElementById("dGEMail");var f=document.getElementById("dGVerEMail");d.style.border="";verifyNameData()||(d.style.border="2px solid red",e=!1);dGMName.style.border="";c.style.border="";f.style.border="";verifyEmailData()||(c.style.border="2px solid red",f.style.border="2px solid red",e=!1);d=document.getElementById("dGAddress4");f=document.getElementById("dGAddress5");
var g=document.getElementById("dGAddress6"),k=document.getElementById("dGAddress7"),h=document.getElementById("dGAddress8");d.style.border="";f.style.border="";g.style.border="";k.style.border="";h.style.border="";verifyBillingData()||(d.style.border="2px solid red",f.style.border="2px solid red",g.style.border="2px solid red",k.style.border="2px solid red",h.style.border="2px solid red",e=!1);if(e){document.getElementById("total");e=document.getElementById("PPprice");var l=document.getElementById("PPnumber");
document.getElementById("paypalElt");var m=calcShoppingCartTotal(0);e.innerHTML="$"+m;l.innerHTML=" for "+b+" items <br>Please check your email for verification.";otherCharges=getOtherCharges(c.value,a,dGMName.value,d.value,f.value,g.options[g.selectedIndex].value,k.value,h.options[h.selectedIndex].value,storeAndChargeF)}}else b.style.visibility="hidden"}}
function storeAndChargeF(a){parms=storeAndChargePass;var b=JSON.parse(a);a=b.costs.tax;b=b.costs.shipping;PAYMENT_BEING_PROCESSED=!0;storeAccount(parms[0],parms[1],parms[2],parms[3],parms[4],parms[5],parms[6],parms[7],parms[8]);paypalElt=document.getElementById("paypalElt");paypalElt.style.display="block";var c=calcShoppingCartTotal(0);document.getElementById("PPsubTotal").innerHTML="<br>sub total: "+addDecimal(c)+" ";document.getElementById("PPshipping").innerHTML="<br>shipping: "+addDecimal(b)+
" ";0<a&&(document.getElementById("PPtax").innerHTML="<br>tax: "+addDecimal(a)+" ");setUpPayPal((100*c+100*b+100*a)/100,parms[0])}function stateExclude(a){for(var b="AA AE AP AS FM GU".split(" "),c=0;c<b.length;c++)if(a==b[c])return!0;return!1}
function moveCountryData(a){countryList=JSON.parse(a);dGAddress6=document.getElementById("dGAddress6");dGAddress8=document.getElementById("dGAddress8");for(var b=a=0;b<countryList.length;b++)if("US"==countryList[b].code){a=b;break}for(b=0;b<countryList[a].states.length;b++)if(!stateExclude(countryList[a].states[b].code)){var c=document.createElement("option");c.text=countryList[a].states[b].name;c.value=countryList[a].states[b].code;dGAddress6.add(c)}CountryInclude=[{country:"United States",code:"US"},
{country:"Israel",code:"IS"}];for(b=0;b<CountryInclude.length;b++)c=document.createElement("option"),c.text=CountryInclude[b].country,c.value=CountryInclude[b].code,dGAddress8.add(c);dGAddress6.selectedIndex=0;dGAddress8.selectedIndex=0}
function getCustomerInfo(){if(calcShoppingCartTotal()){document.getElementById("total");var a=document.getElementById("dataGather"),b=document.getElementById("payButton");a.style.visibility="visible";a=document.getElementById("dGName");var c=document.getElementById("dGEMail"),e=document.getElementById("dGVerEMail"),d=document.getElementById("dGMName"),f=document.getElementById("dGAddress4"),g=document.getElementById("dGAddress5"),k=document.getElementById("dGAddress6"),h=document.getElementById("dGAddress7"),
l=document.getElementById("dGAddress8");a.value="";c.value="";e.value="";d.value="";f.value="";g.value="";k.value="";h.value="";l.value="";b.disabled=!0;b.style.visible="hidden"}}function verifyNameData(){var a=document.getElementById("dGName"),b=document.getElementById("dGMName");1>b.value.length&&0<a.value.length&&(b.value=a.value);return 0<a.value.length?!0:!1}
function verifyEmailData(){var a=document.getElementById("dGEMail"),b=document.getElementById("dGVerEMail");return a.value.toLowerCase()==b.value.toLowerCase()&&0<a.value.length?!0:!1}
function verifyBillingData(){var a=document.getElementById("dGAddress4"),b=document.getElementById("dGAddress5"),c=document.getElementById("dGAddress6"),e=document.getElementById("dGAddress7"),d=document.getElementById("dGAddress8");return 0<a.value.length&&0<b.value.length&&0<c.selectedIndex&&0<e.value.length&&0<d.value.length?!0:!1}var merchPass=[];
function storeOrder(){var a=document.getElementById("outdiv"),b=document.getElementById("orderWork");a=JSON.parse(a.innerHTML);orderIDCollection=[];for(var c=0;c<merchPass.length;c++)sendString=formatOrder(a.accountID,a.targetID,merchPass[c][4],merchPass[c][5],merchPass[c][2],merchPass[c][1],merchPass[c][3],"false"),dbOrder("insert",b,sendString.replace(/\s/g,""),function(){})}
function storeAccount(a,b,c,e,d,f,g,k,h){c=document.getElementById("outdiv");merchPass=b;a=formatAccount(a,e,d,f,g,k,h);dbAccount("insert",c,a,storeOrder)}function formatOrderAPI(a){var b={},c=[];a=a[1];for(entry in a)c.push({sync_variant_id:a[entry][4],quantity:parseInt(a[entry][1])});b.recipient={name:storeAndChargePass[3],address1:storeAndChargePass[4],city:storeAndChargePass[5],state_code:storeAndChargePass[6],country_code:storeAndChargePass[8],zip:storeAndChargePass[7]};b.items=c;return b}
function fromOrderString(a){var b="name="+a.recipient.name;b+="&address1="+a.recipient.address1;b+="&city="+a.recipient.city;b+="&state_code="+a.recipient.state_code;b+="&country_code="+a.recipient.country_code;b+="&zip="+a.recipient.zip;for(var c=0;c<a.items.length;c++)c?(b+="&sync_variant_id"+c+"="+a.items[c].sync_variant_id,b+="&quantity"+c+"="+a.items[c].quantity):(b+="&sync_variant_id="+a.items[0].sync_variant_id,b+="&quantity="+a.items[0].quantity);return b}var storeAndChargePass=[];
function getOtherCharges(a,b,c,e,d,f,g,k,h){storeAndChargePass=[a,b,!1,c,e,d,f,g,k];data=formatOrderAPI(storeAndChargePass);dataString=fromOrderString(data);getPFApiData(function(){}).getOrderEstimate(dataString,h)};
