function getSize(a){if("XS"==a)return"Extra Small";if("S"==a)return"Small";if("M"==a)return"Medium";if("L"==a)return"Large";if("XL"==a)return"Extra Large";if("2XL"==a)return"Double Extra Large";if("3XL"==a)return"Triple Extra Large";if("4XL"==a)return"Four Times Extra Large";if("5XL"==a)return"Five Times Extra Large"}
function getSizeCode(a){if("Extra Small"==a)return"XS";if("Small"==a)return"S";if("Medium"==a)return"M";if("Large"==a)return"L";if("Extra Large"==a)return"XL";if("Double Extra Large"==a)return"2XL";if("Triple Extra Large"==a)return"3XL";if("Four Times Extra Large"==a)return"4XL";if("Five Times Extra Large"==a)return"5XL"}function getTwoDigits(a){return 10>a?"0"+a:""+a}
function getColorButtonList(a){for(var b=[],c=0;50>c;c++)if(document.getElementById("Color"+getSuffix(c)+a)){var d=document.getElementById("Color"+getSuffix(c)+a);d.style.background;b.push(d)}else break;return b}function colorAllButtons(a){bList=getColorButtonList(a);for(i=0;i<bList.length;i++)bList[i]&&(bList[i].style.background="#"+bList[i].getAttribute("hexVAL"),bList[i].style.color="#"+bList[i].getAttribute("hexVAL"),bList[i].style.border="2px solid orange",bList[i].chosen=!1)}
function displayProperSizes(a,b){possibleArray={XS:0,S:0,M:0,L:0,XL:0,"2XL":0,"3XL":0,"4XL":0,"5XL":0};for(var c=0;c<a.length;c++)possibleArray[a[c]]=1;for(size in possibleArray)possibleArray[size]?(sizeElt=document.getElementById(size+b),sizeElt.style.display="inline"):document.getElementById(size+b)&&(sizeElt=document.getElementById(size+b),sizeElt.style.display="none")}
function displayProperColors(a,b){possibleArray={};MAX_COLORS=25;for(var c=0;c<COLOR_CODES.length;c++)possibleArray["#"+COLOR_CODES[c].HEX]=!1;for(c=0;c<a.length;c++)possibleArray["#"+getHex(a[c].replace("^"," "))]=!0;for(c=0;c<MAX_COLORS;c++)id="Color-"+getTwoDigits(c)+b,document.getElementById(id)&&(colorElt=document.getElementById(id),hexVal=colorElt.getAttribute("hexval"),colorElt.style.display=possibleArray[hexVal]?"inline":"none")}
function scoreColorButton(a,b,c){a.substring(0,a.length-3);var d=a.substring(a.length-3,a.length),e=document.getElementById("bigPicture"+d);e.style.display="block";e.style.width="60%";e.style.height="60%";e.style.top="10%";e.style.right="2%";e.style.padding="2%";e.style.border="0px";colorAllButtons(d);var f=document.getElementById("color"+d);a=document.getElementById(a);var g=a.getAttribute("allVariantSizes");f.setAttribute("allVariantSizes",g);a.style.background="#"+a.getAttribute("hexVAL");a.style.color=
"#"+a.getAttribute("hexVAL");a.style.border="4px solid black";a.chosen=!0;f.innerHTML=b.replace(/\^/g," ");document.getElementById("productNumber"+d);document.getElementById("frontImg"+d);e.innerHTML="<img class=noborder src='"+a.getAttribute("preview"+d)+"'/>";e.onclick=closeBigPicture;displayProperSizes(c,d);setTimeout(function(){e.style.display="none"},7E3);document.getElementById("productNumber"+d)}
function closeBigPicture(){for(var a=0;15>a;a++){var b=getSuffix(a);if(b=document.getElementById("bigPicture"+b))b.style.display="none"}}function setPricing(a,b){var c=getCurrentProduct(b);document.getElementById("priceTag"+b).innerHTML="$"+extractVariantPrice(a,PRINTFUL_DATA[c])}function getCurrentProduct(a){return document.getElementById("productNumber"+a).innerHTML}
function scoreButton(a,b){var c=a.substring(0,a.length-3),d=a.substring(a.length-3,a.length),e=getButtonList(d),f=document.getElementById("size"+d);for(i=0;i<e.length;i++)e[i]&&(e[i].style.background="white",e[i].style.color="black",e[i].chosen=!1);a=document.getElementById(a);a.style.background="black";a.style.color="white";a.chosen=!0;f.innerHTML=getSize(c);displayProperColors(b,d)}function getSizeInfo(a,b){return getSizeArray(a,b)}BACK_CLICK=[!1,!1,!1,!1,!1,!1,!1,!1,!1];
function showBack(a,b){var c=parseInt(b.substring(1));BACK_CLICK[c]=!1;a&&(BACK_CLICK[c]=!0);a=document.getElementById("frontImg"+b);c=document.getElementById("back"+b);var d=document.getElementById("backImg"+b);b=document.getElementById("shirtBack"+b);c.style.background=a.style.background;d.style.background=a.style.background;c.classList.contains("noshow")&&(b.classList.remove("noshow"),c.classList.remove("noshow"))}
function hideBack(a){var b=parseInt(a.substring(1));BACK_CLICK[b]||(b=document.getElementById("back"+a),a=document.getElementById("shirtBack"+a),b.classList.add("noshow"),a.classList.add("noshow"))};
