function logPayment(c,d,a){var f="amtPaid="+a.amtPaid+"&pmtStatus="+a.pmtStatus+"&firstName="+a.firstName.replace(/\s/g,"*")+"&lastName="+a.lastName.replace(/\s/g,"*")+"&email="+a.email.replace(/\s/g,"*")+"&address_line_1="+a.address_line_1.replace(/\s/g,"*")+"&address_line_2="+a.address_line_2.replace(/\s/g,"*")+"&city="+a.city.replace(/\s/g,"*")+"&state="+a.state.replace(/\s/g,"*")+"&postal_code="+a.postal_code.replace(/\s/g,"*")+"&country_code="+a.country_code.replace(/\s/g,"*")+"&reference_id="+
a.reference_id+"&id="+a.id+"&totalCharged="+c+"&oldEmail="+d;ppLog("insert",outDiv,f.replace(/\s/g,""),function(){});markOrderPaid(c,d,a.amtPaid)}var orderTotal=0,emailPass="";function markOrderPaid(c,d,a){emailPass=d;orderTotal=c;dbAccount("select",outDiv,"email="+d,getOrders)}function getOrders(){accountData=outDiv.innerHTML;dbOrder("select",outDiv,"accountID="+accountData,updateOrders)}
function updateOrders(){orderData=JSON.parse(outDiv.innerHTML);for(i=totalDue=0;i<orderData.length;i++)totalDue+=parseInt(orderData[i].price)*parseInt(orderData[i].Number);totalDue>orderTotal?(doMail("oops",emailPass,function(){}),console.log("something went wrong with the payment amount")):doMail("thanks",emailPass,function(){});for(i=0;i<orderData.length;i++)dbOrder("update",outDiv,"orderID="+orderData[i].orderID+"&paidFlag=1",function(){})}
function cancelAction(){PAYMENT_BEING_PROCESSED=!1;getReadyForPayPal(0);paypalElt=document.getElementById("paypalElt");paypalElt.style.display="none"}
function actionAfterPayment(c,d,a,f){PAYMENT_BEING_PROCESSED=!1;getReadyForPayPal(0);paypalElt=document.getElementById("paypalElt");paypalElt.style.display="none";f.amtPaid>=d?(apiCall(outDiv,function(){},"order",0),logPayment(d,a,f),window.open("https://NameThatThing.site/paidThanks.html?AMOUNT="+d+"&email"+a+"_blank,resizable=yes")):window.open("https://NameThatThing.site/paidOops.html?AMOUNT="+d+"&email"+a+"_blank,resizable=yes")}
function __setUpPayPal(c,d){details={};details.amtPaid=c;details.pmtStatus="TESTSTATUS";details.firstName="Efraim";details.lastName="Krug";details.email="TestEmail@gmail.com";details.address_line_1="323 Test address";details.address_line_2="Building #3/4";details.city="Los Angeles";details.state="CA";details.postal_code="90003";details.country_code="US";details.reference_id="Very-Long-Reference-ID";details.id="999999999";actionAfterPayment(0,c,d,details)}
function extractData(c,d,a){c[d]=a;return c}
function setUpPayPal(c,d){document.getElementById("output");var a=c?c:"18.00";paypal.Buttons({style:{shape:"pill",color:"blue",layout:"horizontal",label:"paypal",tagline:"true"},createOrder:function(d,c){return c.order.create({purchase_units:[{amount:{value:a}}]})},onApprove:function(f,g){return g.order.capture().then(function(e){e=JSON.parse(e);var b=extractData({},"amtPaid",e.purchase_units[0].payments.captures[0].amount.value);b=extractData(b,"pmtStatus",e.purchase_units[0].payments.captures[0].status);
b=extractData(b,"firstName",e.payer.name.given_name);b=extractData(b,"lastName",e.payer.name.surname);b=extractData(b,"email",e.payer.email_address);b=extractData(b,"address_line_1",e.purchase_units[0].shipping.address.address_line_1);b=extractData(b,"address_line_2",e.purchase_units[0].shipping.address.address_line_2);b=extractData(b,"city",e.purchase_units[0].shipping.address.admin_area_2);b=extractData(b,"state",e.purchase_units[0].shipping.address.admin_area_1);b=extractData(b,"postal_code",e.purchase_units[0].shipping.address.postal_code);
b=extractData(b,"country_code",e.purchase_units[0].shipping.address.country_code);b=extractData(b,"reference_id",e.purchase_units[0].reference_id);b=extractData(b,"id",e.id);actionAfterPayment(a,c,d,b)})},onCancel:function(a){cancelAction()}}).render("#paypal-button-container")};
