java -jar compiler.jar --js colorCodes.js --js_output_file colorCodes-compiled.js
java -jar compiler.jar --js compiled --js_output_file compiled-compiled.js
java -jar compiler.jar --js dataCollection.js --js_output_file dataCollection-compiled.js
java -jar compiler.jar --js doMail.js --js_output_file doMail-compiled.js
java -jar compiler.jar --js getPFAPIData.js --js_output_file getPFAPIData-compiled.js
java -jar compiler.jar --js gooten-js --js_output_file gooten-compiled.js
java -jar compiler.jar --js HTMLTemplates.js --js_output_file HTMLTemplates-compiled.js
java -jar compiler.jar --js HTMLTemplatesRW.js --js_output_file HTMLTemplatesRW-compiled.js
java -jar compiler.jar --js menu.js --js_output_file menu-compiled.js
java -jar compiler.jar --js menuRW.js --js_output_file menuRW-compiled.js
java -jar compiler.jar --js oldJS2.js --js_output_file oldJS2-compiled.js
java -jar compiler.jar --js oldJS2RW.js --js_output_file oldJS2RW-compiled.js
java -jar compiler.jar --js PDSBAction.js --js_output_file PDSBAction-compiled.js
java -jar compiler.jar --js PDSBActionRW.js --js_output_file PDSBActionRW-compiled.js
java -jar compiler.jar --js PDSBCart.js --js_output_file PDSBCart-compiled.js
java -jar compiler.jar --js PDSBProductDisplay.js --js_output_file PDSBProductDisplay-compiled.js
java -jar compiler.jar --js PDSBUtilities.js --js_output_file PDSBUtilities-compiled.js
java -jar compiler.jar --js PrintFulAPI.js --js_output_file PrintFulAPI-compiled.js
java -jar compiler.jar --js PrintFulAPIRW.js --js_output_file PrintFulAPIRW-compiled.js
java -jar compiler.jar --js PrintFulAPIStuff.js --js_output_file PrintFulAPIStuff-compiled.js
java -jar compiler.jar --js PrintFulAPIStuffRW.js --js_output_file PrintFulAPIStuffRW-compiled.js
java -jar compiler.jar --js productSkel.js --js_output_file productSkel-compiled.js
java -jar compiler.jar --js productSkelWork.js --js_output_file productSkelWork-compiled.js
java -jar compiler.jar --js SBdataBase.js --js_output_file SBdataBase-compiled.js
java -jar compiler.jar --js SBpayPal.js --js_output_file SBpayPal-compiled.js
java -jar compiler.jar --js sizingInfo.js --js_output_file sizingInfo-compiled.js
